export const UPDATE_TRANSFER_IN = "UPDATE_TRANSFER_IN"
export const ADD_TRANSFER_IN = 'ADD_TRANSFER_IN'
export const REMOVE_TRANSFER_IN = 'REMOVE_TRANSFER_IN'
export const ADD_SERVICE_IN = 'ADD_SERVICE_IN'
export const REMOVE_SERVICE_IN = 'REMOVE_SERVICE_IN'
//
export const UPDATE_TRANSFER_OUT = "UPDATE_TRANSFER_OUT"
export const ADD_TRANSFER_OUT = "ADD_TRANSFER_OUT"
export const REMOVE_TRANSFER_OUT = "REMOVE_TRANSFER_OUT"
export const ADD_SERVICE_OUT = "ADD_SERVICE_OUT"
export const REMOVE_SERVICE_OUT = "REMOVE_SERVICE_OUT"