export const UPDATE_TRANSFER_IN = "UPDATE_TRANSFER_IN"
export const ADD_TRANSFER_IN = 'ADD_TRANSFER_IN'
export const REMOVE_TRANSFER_IN = 'REMOVE_TRANSFER_IN'
export const ADD_SERVICE_IN = 'ADD_SERVICE_IN'
export const REMOVE_SERVICE_IN = 'REMOVE_SERVICE_IN'
//
export const UPDATE_TRANSFER_OUT = "UPDATE_TRANSFER_OUT"
export const ADD_TRANSFER_OUT = "ADD_TRANSFER_OUT"
export const REMOVE_TRANSFER_OUT = "REMOVE_TRANSFER_OUT"
export const ADD_SERVICE_OUT = "ADD_SERVICE_OUT"
export const REMOVE_SERVICE_OUT = "REMOVE_SERVICE_OUT"
//Action transfer by event(restaurant)
export const UPDATE_TRANSFER_EVENT = "UPDATE_TRANSFER_EVENT"
export const ADD_TRANSFER_EVENT  = "ADD_TRANSFER_EVENT"
export const REMOVE_TRANSFER_EVENT = "REMOVE_TRANSFER_EVENT"
export const RESET_TRANSFER_EVENT = "RESET_TRANSFER_EVENT"
export const ADD_SERVICE_EVENT = "ADD_SERVICE_EVENT"
export const REMOVE_SERVICE_EVENT = "REMOVE_SERVICE_EVENT"